// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjd4AdwvyVa-VAipZC02z816wuG2Ya2o8',
    appId: '1:236350832956:web:9f4c91965b7fbad9681e39',
    messagingSenderId: '236350832956',
    projectId: 'eventvelyapp',
    authDomain: 'eventvelyapp.firebaseapp.com',
    storageBucket: 'eventvelyapp.firebasestorage.app',
    measurementId: 'G-BBD3CR2355',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxMATP-eJrc33aFuz90hVGNxQBX9w7Oaw',
    appId: '1:236350832956:android:f881e8b6fa28c4e3681e39',
    messagingSenderId: '236350832956',
    projectId: 'eventvelyapp',
    storageBucket: 'eventvelyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI-6fT61xDl42fd-a8Q_-BrmTwwoUlr2U',
    appId: '1:236350832956:ios:f64662b3f24916c8681e39',
    messagingSenderId: '236350832956',
    projectId: 'eventvelyapp',
    storageBucket: 'eventvelyapp.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI-6fT61xDl42fd-a8Q_-BrmTwwoUlr2U',
    appId: '1:236350832956:ios:f64662b3f24916c8681e39',
    messagingSenderId: '236350832956',
    projectId: 'eventvelyapp',
    storageBucket: 'eventvelyapp.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjd4AdwvyVa-VAipZC02z816wuG2Ya2o8',
    appId: '1:236350832956:web:c7f0787cb1682578681e39',
    messagingSenderId: '236350832956',
    projectId: 'eventvelyapp',
    authDomain: 'eventvelyapp.firebaseapp.com',
    storageBucket: 'eventvelyapp.firebasestorage.app',
    measurementId: 'G-8M0067FGGD',
  );
}
